[build-system]
requires = ["uv_build>=0.12.17,<0.13"]
build-backend = "uv_build"

[project]
name = "rss-digest"
version = "0.1"
dependencies = [
    'reader',
    'jinja2',
    'platformdirs',
    'lxml',
    'requests',
    'sphinx',
    'pytz',
    'beautifulsoup4',
    "sgmllib3k>=1.0.0",
]
authors = [
  { name="bunburya", email="dev@bunburya.eu" },
]
description = "Generate digests of subscribed RSS and Atom feeds."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
"Homepage" = "https://github.com/bunburya/rss-digest"

[project.scripts]
rss-digest = "rss_digest:main"

[dependency-groups]
dev = [
    "lxml-stubs>=0.5.1",
    "pytest>=8.4.2",
]
