#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import argparse

from rss_digest.cli import CLI
from rss_digest.rss_digest import RSSDigest



def main():
    cli = CLI()
    parser = get_arg_parser(cli)
    parser.parse_args(sys.argv[1:])
    
if __name__ == '__main__':
    
    main()
