import unittest

from rss_digest.resources.helpers import html2text

HTML_1 = """&lt;!-- SC_OFF --&gt;&lt;div class=&quot;md&quot;&gt;&lt;p&gt;original post &lt;a href=&quot;https://www.reddit.com/r/rss/comments/fvg3ed/i_built_a_better_rss_feed_for_reddit/&quot;&gt;https://www.reddit.com/r/rss/comments/fvg3ed/i_built_a_better_rss_feed_for_reddit/&lt;/a&gt;&lt;/p&gt; &lt;p&gt;I&amp;#39;ve noticed many of the users of my improved rss feed for reddit are using it for... videos, gifs, and images.&lt;/p&gt; &lt;p&gt;I&amp;#39;ve made some improvements in this department.&lt;/p&gt; &lt;p&gt;&lt;a href=&quot;https://i.imgur.com/w85gSGM.png&quot;&gt;grid view&lt;/a&gt; // &lt;a href=&quot;https://i.imgur.com/EvjfqhY.png&quot;&gt;post view&lt;/a&gt;&lt;/p&gt; &lt;ol&gt; &lt;li&gt;Now it try&amp;#39;s to detect image and video content and embed it into feedly!&lt;/li&gt; &lt;li&gt;If your feed reader supports iframes (feedly does) it will even embed gfycat and &lt;a href=&quot;https://v.redd.it&quot;&gt;v.redd.it&lt;/a&gt; content.&lt;/li&gt; &lt;li&gt;If there are other popular video formats you want me to try and embed let me know.&lt;/li&gt; &lt;/ol&gt; &lt;p&gt;If you are interested in using it to you:&lt;/p&gt; &lt;ol&gt; &lt;li&gt;Go to a subreddit or meta feed you like example: &lt;a href=&quot;https://www.reddit.com/r/aww/&quot;&gt;https://www.reddit.com/r/aww/&lt;/a&gt;&lt;/li&gt; &lt;li&gt;Add .json onto the end: &lt;a href=&quot;https://www.reddit.com/r/aww.json&quot;&gt;https://www.reddit.com/r/aww.json&lt;/a&gt;&lt;/li&gt; &lt;li&gt;Change the domain name to, &lt;a href=&quot;https://reddit.0qz.fun/&quot;&gt;reddit.0qz.fun&lt;/a&gt; like: &lt;a href=&quot;https://reddit.0qz.fun/r/aww.json&quot;&gt;https://reddit.0qz.fun/r/aww.json&lt;/a&gt;&lt;/li&gt; &lt;li&gt;Subscribe to ^^^ that url in your favorite feed reader.&lt;/li&gt; &lt;/ol&gt; &lt;/div&gt;&lt;!-- SC_ON --&gt; &amp;#32; submitted by &amp;#32; &lt;a href=&quot;https://www.reddit.com/user/still-standing&quot;&gt; /u/still-standing &lt;/a&gt; &lt;br/&gt; &lt;span&gt;&lt;a href=&quot;https://www.reddit.com/r/rss/comments/galitc/my_improved_reddit_rss_feed_now_support_videos/&quot;&gt;[link]&lt;/a&gt;&lt;/span&gt; &amp;#32; &lt;span&gt;&lt;a href=&quot;https://www.reddit.com/r/rss/comments/galitc/my_improved_reddit_rss_feed_now_support_videos/&quot;&gt;[comments]&lt;/a&gt;&lt;/span&gt;"""
HTML_2 = """&lt;!-- SC_OFF --&gt;&lt;div class=&quot;md&quot;&gt;&lt;p&gt;My saved links on here got pretty huge so was looking to export them into excel where I can more easily search through them. Problem is the feed only gives the first 25 and I don&amp;#39;t know how to go beyond that. I haven&amp;#39;t found anything for how to do this with saved feeds.&lt;/p&gt; &lt;/div&gt;&lt;!-- SC_ON --&gt; &amp;#32; submitted by &amp;#32; &lt;a href=&quot;https://www.reddit.com/user/Akaida&quot;&gt; /u/Akaida &lt;/a&gt; &lt;br/&gt; &lt;span&gt;&lt;a href=&quot;https://www.reddit.com/r/rss/comments/odygj3/getting_results_for_saved_link_rss_feed_past/&quot;&gt;[link]&lt;/a&gt;&lt;/span&gt; &amp;#32; &lt;span&gt;&lt;a href=&quot;https://www.reddit.com/r/rss/comments/odygj3/getting_results_for_saved_link_rss_feed_past/&quot;&gt;[comments]&lt;/a&gt;&lt;/span&gt;"""
HTML_3 = """&lt;!-- SC_OFF --&gt;&lt;div class=&quot;md&quot;&gt;&lt;p&gt;Downloaded the latest appimage package release from github and it works fine, but when new messages are downloaded a notification will appear but not play any sound whatsoever, any way to change that?&lt;/p&gt; &lt;/div&gt;&lt;!-- SC_ON --&gt; &amp;#32; submitted by &amp;#32; &lt;a href=&quot;https://www.reddit.com/user/Spookum&quot;&gt; /u/Spookum &lt;/a&gt; &lt;br/&gt; &lt;span&gt;&lt;a href=&quot;https://www.reddit.com/r/rss/comments/ocquba/rssguard_notifications_on_ubuntu_2104_x8664_linux/&quot;&gt;[link]&lt;/a&gt;&lt;/span&gt; &amp;#32; &lt;span&gt;&lt;a href=&quot;https://www.reddit.com/r/rss/comments/ocquba/rssguard_notifications_on_ubuntu_2104_x8664_linux/&quot;&gt;[comments]&lt;/a&gt;&lt;/span&gt;"""


class HelperTestCase(unittest.TestCase):
    def test_html2text(self):
        for h in (HTML_1, HTML_2, HTML_3):
            # Just check that the function calls correctly without error
            # (TODO: Validate output in some way?)
            text = html2text(h)
            print('TEXT IS:')
            print(text)

if __name__ == '__main__':
    unittest.main()
